source 'https://github.com/CocoaPods/Specs.git'

target 'CtrlZ-Example', :exclusive => true do
  pod "CtrlZ", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CtrlZ", :path => "../"

  
end
